version: '3.3'
services:
  db:
    image: mariadb
    environment:
      - MYSQL_USER=dbwt
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=dbwt
    ports:
      - "0.0.0.0:3306:3306"
    volumes:
     - ./docker-data/database:/var/lib/mysql
    networks:
      - back
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - back
      - front

networks:
  front:
     driver: bridge
  back:
     driver: bridge
